// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Tue Jun 04 07:18:16 2019

CSRRegisters CSRRegisters_inst
(
	.iCLK(iCLK_sig) ,	// input  iCLK_sig
	.iRST(iRST_sig) ,	// input  iRST_sig
	.iREGWrite(iREGWrite_sig) ,	// input  iREGWrite_sig
	.iNumReg(iNumReg_sig) ,	// input [6:0] iNumReg_sig
	.iWriteData(iWriteData_sig) ,	// input [31:0] iWriteData_sig
	.iPC(iPC_sig) ,	// input [31:0] iPC_sig
	.iUcause(iUcause_sig) ,	// input [31:0] iUcause_sig
	.oUTVEC(oUTVEC_sig) ,	// output [31:0] oUTVEC_sig
	.oCSRInstOut(oCSRInstOut_sig) 	// output [31:0] oCSRInstOut_sig
);

